
apiVersion: batch/v1
kind: Job
metadata:
  name: echo-job

spec:
  template: # template for each pod
    spec:
      restartPolicy: OnFailure
      containers:
      - image: busybox
        name: echo-job
        imagePullPolicy: IfNotPresent
        env:
          - name: os
            value: "ubuntu"
          - name: echo_arg
            value: "world"
        command:
          - /bin/echo
        args: ["hello", $(echo_arg)]
